services:
  airport_service:
    build: ./airport_service
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: airport_service
    command: flask run -h 0.0.0.0 -p 5001

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  db_data: